name: Gitartwork

on:
  push:

permissions:
  contents: write

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Gitartwork
        uses: jasineri/gitartwork@v1
        with:
          user_name: sorashree
          text: SHREEYA

      - name: Push Gitartwork
        uses: jasineri/simple-push-action@v1
