name: Gitartwork

on:
  push:

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Gitartwork
        uses: jasineri/gitartwork@v1
        with:
          # Your GitHub username
          user_name: sorashree

          # Text displayed on the artwork
          text: SHREEYA

      - name: Push Gitartwork
        uses: jasineri/simple-push-action@v1